# Generated by Django 5.2.2 on 2025-06-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseArticle",
            fields=[
                ("kb_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
