# Generated by Django 5.2.2 on 2025-06-09 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0006_ticket_agent_processed_ticket_agent_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseArticle",
            fields=[
                (
                    "kb_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.IntegerField(default=0)),
                ("helpful_votes", models.IntegerField(default=0)),
                ("total_votes", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMResponse",
            fields=[
                (
                    "response_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("TICKET", "Ticket Resolution"),
                            ("KB", "Knowledge Base"),
                            ("GENERAL", "General Query"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("helpful_votes", models.IntegerField(default=0)),
                ("total_votes", models.IntegerField(default=0)),
                (
                    "related_kb_articles",
                    models.ManyToManyField(
                        blank=True, to="knowledge_base.knowledgebasearticle"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
