from django.urls import path
from .views import (
    ticket_analytics,
    process_with_agent,
    task_status,
    ticket_agent_status,
    create_ticket,
    clarify_ticket,
    feedback_ticket,
    ticket_history,
    list_tickets,
    get_ticket,
    update_ticket,
    search_tickets,
    upload_attachment,
    add_comment,
    escalate_ticket,
    assign_ticket,
    update_ticket_status,
    agent_dashboard,
    bulk_update_tickets,
    suggest_kb_articles,
    add_internal_note,
    audit_log,
    ai_suggestions
)

urlpatterns = [
    # Add ticket-related endpoints here
    path("analytics/", ticket_analytics, name="ticket-analytics"),
    path("<int:ticket_id>/process/", process_with_agent, name="process-with-agent"),
    path("tasks/<str:task_id>/status/", task_status, name="task-status"),
    path("<int:ticket_id>/agent-status/", ticket_agent_status, name="ticket-agent-status"),
    path("", create_ticket, name="create-ticket"),
    path("list/", list_tickets, name="list-tickets"),
    path("<int:ticket_id>/", get_ticket, name="get-ticket"),
    path("<int:ticket_id>/update/", update_ticket, name="update-ticket"),
    path("<int:ticket_id>/clarify/", clarify_ticket, name="clarify-ticket"),
    path("<int:ticket_id>/feedback/", feedback_ticket, name="feedback-ticket"),
    path("<int:ticket_id>/history/", ticket_history, name="ticket-history"),
    path("search/", search_tickets, name="search-tickets"),
    path("<int:ticket_id>/upload/", upload_attachment, name="upload-attachment"),
    path("<int:ticket_id>/comment/", add_comment, name="add-comment"),
    path("<int:ticket_id>/escalate/", escalate_ticket, name="escalate-ticket"),
    path("<int:ticket_id>/assign/", assign_ticket, name="assign-ticket"),
    path("<int:ticket_id>/status/", update_ticket_status, name="update-ticket-status"),
    path("dashboard/", agent_dashboard, name="agent-dashboard"),
    path("bulk-update/", bulk_update_tickets, name="bulk-update-tickets"),
    path("<int:ticket_id>/kb-suggestions/", suggest_kb_articles, name="suggest-kb-articles"),
    path("<int:ticket_id>/internal-note/", add_internal_note, name="add-internal-note"),
    path("<int:ticket_id>/audit-log/", audit_log, name="audit-log"),
    path("<int:ticket_id>/ai-suggestions/", ai_suggestions, name="ai-suggestions"),
]
