# Generated by Django 5.2.2 on 2025-06-09 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                ("solution_id", models.AutoField(primary_key=True, serialize=False)),
                ("steps", models.TextField()),
                ("worked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score of the solution (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_solutions",
                        to="users.user",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_solutions",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeBaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("solution", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wifi", "Wi-Fi"),
                            ("laptop", "Laptop"),
                            ("vpn", "VPN"),
                            ("printer", "Printer"),
                            ("email", "Email"),
                            ("software", "Software"),
                            ("hardware", "Hardware"),
                            ("network", "Network"),
                            ("account", "Account"),
                            ("access", "Access"),
                            ("phone", "Phone"),
                            ("server", "Server"),
                            ("security", "Security"),
                            ("cloud", "Cloud"),
                            ("storage", "Storage"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score of the solution (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "ticket",
                    models.OneToOneField(
                        blank=True,
                        help_text="Reference to the original ticket (if this entry came from a ticket)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_entry",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_kb_entries",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Entry",
                "verbose_name_plural": "Knowledge Base Entries",
                "indexes": [
                    models.Index(
                        fields=["category"], name="solutions_k_categor_ce4b17_idx"
                    ),
                    models.Index(
                        fields=["issue_type"], name="solutions_k_issue_t_c3726f_idx"
                    ),
                    models.Index(
                        fields=["confidence_score"],
                        name="solutions_k_confide_9f77b4_idx",
                    ),
                    models.Index(
                        fields=["verified"], name="solutions_k_verifie_293a5e_idx"
                    ),
                ],
            },
        ),
    ]
