# Generated by Django 5.2.2 on 2025-06-05 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                ("solution_id", models.AutoField(primary_key=True, serialize=False)),
                ("steps", models.TextField()),
                ("worked", models.BooleanField(default=False)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket"
                    ),
                ),
            ],
        ),
    ]
