# Generated by Django 5.2.2 on 2025-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationTask",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("command", models.CharField(max_length=100)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(max_length=50)),
                ("result", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
