# Generated by Django 5.2.2 on 2025-06-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("issue_type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("screenshot", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wifi", "Wi-Fi"),
                            ("laptop", "Laptop"),
                            ("vpn", "VPN"),
                            ("printer", "Printer"),
                            ("email", "Email"),
                            ("software", "Software"),
                            ("hardware", "Hardware"),
                            ("network", "Network"),
                            ("account", "Account"),
                            ("access", "Access"),
                            ("phone", "Phone"),
                            ("server", "Server"),
                            ("security", "Security"),
                            ("cloud", "Cloud"),
                            ("storage", "Storage"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_response",
                    models.JSONField(
                        blank=True,
                        help_text="Response from the AI agent analyzing this ticket",
                        null=True,
                    ),
                ),
                (
                    "agent_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the AI agent has processed this ticket",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to="users.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
