# Generated by Django 5.2.2 on 2025-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
