# Generated by Django 5.2.2 on 2025-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="screenshot",
            field=models.URLField(blank=True, null=True),
        ),
    ]
