# Generated by Django 5.2.2 on 2025-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("wifi", "Wi-Fi"),
                    ("laptop", "Laptop"),
                    ("vpn", "VPN"),
                    ("printer", "Printer"),
                    ("email", "Email"),
                    ("software", "Software"),
                    ("hardware", "Hardware"),
                    ("network", "Network"),
                    ("account", "Account"),
                    ("access", "Access"),
                    ("phone", "Phone"),
                    ("server", "Server"),
                    ("security", "Security"),
                    ("cloud", "Cloud"),
                    ("storage", "Storage"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
