# Generated by Django 5.2.2 on 2025-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticket_category_ticket_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="agent_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the AI agent has processed this ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="agent_response",
            field=models.JSONField(
                blank=True,
                help_text="Response from the AI agent analyzing this ticket",
                null=True,
            ),
        ),
    ]
