name: Delete All Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC

permissions:
  actions: write  # ✅ Required for deleting artifacts
  contents: read  # ✅ Default needed for most actions

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 0 days, keep last 0
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 days'
          skip-recent: 0
